# Port untuk koneksi
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
mode: rule
bind-address: '*'
external-controller: 0.0.0.0:9090
external-ui: ui
secret: "asdqwe123" 
log-level: info
tun:
  enable: true
  stack: system
  device: nic1
sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
  skip-src-address:
    - 192.168.0.3/32
  skip-dst-address:
    - 192.168.0.3/32
  
# 1. DAFTAR PROXY (Isi dengan akun kamu di sini)
proxies:
  - name: Server-Utama
    server: aws.koneksiku.live
    port: 443
    type: trojan
    password: d6TLRcx2ceyNllpThiox8g
    skip-cert-verify: true
    sni: aws.koneksiku.live
    network: ws
    ws-opts:
      path: /trojan-ws
      headers:
        Host: aws.koneksiku.live
    udp: true

# 2. GROUP PROXY (Pengaturan menu di Clash)
proxy-groups:
  - name: ðŸš€ Proxy-Pilihan
    type: select
    proxies:
      - Server-Utama
      - load-balance
      - DIRECT
  - name: "load-balance"
    type: load-balance
    strategy: round-robin
    proxies:
    - Server-Utama
    - DIRECT
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
  #lazy: true
  #strategy: consistent-hashing # or round-robin
  

# 3. ATURAN (Rules)
rules:
  - DOMAIN-SUFFIX,google.com,ðŸš€ Proxy-Pilihan
  - DOMAIN-KEYWORD,facebook,ðŸš€ Proxy-Pilihan
  - GEOIP,CN,DIRECT
  - MATCH,ðŸš€ Proxy-Pilihan
